# hash:sha256:9b54b15c15b682561c6147bca61062558fc93b0bb41a8d835a42707ba0165264
FROM registry.codeocean.allenneuraldynamics.org/codeocean/tensorflow:2.11-python3.10-cuda11.7.0-runtime-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive

ARG GIT_ASKPASS
ARG GIT_ACCESS_TOKEN
COPY git-askpass /

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ffmpeg=7:4.4.2-0ubuntu0.22.04.1 \
        libegl1-mesa=23.0.4-0ubuntu1~22.04.1 \
        libsm6=2:1.2.3-1build2 \
        libxext6=2:1.3.4-1build1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install -U --no-cache-dir \
    facemap[gui]==1.0.4 \
    h5py==3.10.0 \
    matplotlib==3.8.0 \
    natsort==8.4.0 \
    numba==0.58.1 \
    numpy==1.26.1 \
    opencv-python-headless==4.8.1.78 \
    pyqt6==6.5.3 \
    pyqtgraph==0.13.3 \
    qtpy==2.4.1 \
    scikit-learn==1.3.2 \
    scipy==1.11.3 \
    torch==2.1.0 \
    tqdm==4.66.1 \
    umap-learn==0.5.4

COPY postInstall /
RUN /postInstall
